<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= /* @escapeNotVerified */
            __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */
    $viewMode ?> products-<?= /* @escapeNotVerified */
    $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection

                           as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */
                    $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= /* @escapeNotVerified */
                        $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */
                                   $_product->getProductUrl() ?>">
                                    <?php //echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    <?php echo strlen($_helper->productAttribute($_product, $_product->getName(), 'name')) > 50 ? substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 50) . "..." : $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                                
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <!--test-->
                            <div class="price-including-tax" style="display: inline-block" ;>
                                <span>
                                    <?php
                                    $priceWithoutTaxRound = round($_product->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount(), 2);
                                    $priceWithTaxRound = round($_product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue(), 2);
                                    ?>
                                </span>
                            </div>

                            <!--test-->
                            <?= $block->getProductDetailsHtml($_product) ?>
                                <?php
                                    $blockObj= $block->getLayout()->createBlock('Zehntech\HomeProducts\Block\StockBySource');
                                    $qty = $blockObj->getStockQty($_product);
                                ?>
                                <div class="stock-details">
                                    <span><i class="fa fa-circle mr-1 <?= $qty ? 'stock-in' : 'out-stock'; ?>"></i></span>
                                    <span>
                                    <?php if($qty):
                                            echo "På lager"." ".$qty;
                                        else:
                                            echo "Varen er snart PÅ lager igen, bestil blot";
                                        endif;
                                    ?>
                                    </span>
                                </div>
                                <!-- <div class="price-container">
                                    <span class="price-without-tax">
                                        <?php echo $priceWithoutTaxRound; ?>
                                    </span>
                                    <span class="price-with-tax">
                                            <?php echo $priceWithTaxRound; ?><?php echo __('  inkl. moms'); ?>
                                    </span>
                                </div> -->
                            <div class="product-item-inner <?= $viewMode==='list'?'row w-100 m-0':'' ?>">
                                <!--test-->
                                <?php if($viewMode==="list"): ?>
                                <div class="product-extra-details col-md-5 p-0">
                                    <div class="oem list-att"><span>Varenr.: </span><?= $_product->getOem(); ?></div>
                                    <div class="sku list-att"><span>Katalognr.: </span><?= $_product->getSku(); ?></div>
                                    <?php if($_product->getKatalogpage()):?><div class="kat_page list-att"><span>Sidenr.: </span><?= filter_var($_product->getKatalogpage(), FILTER_SANITIZE_NUMBER_INT) ?></div><?php endif; ?>
                                </div>
                            <?php endif; ?>
                                <div class="price-container <?= $viewMode==='list'?'col-md-4 p-0':'' ?>">
                                    <div class="price-without-tax">
                                        <?php echo $priceWithoutTaxRound; ?>
                                    </div>
                                    <div class="price-with-tax">
                                            <?php echo $priceWithTaxRound; ?><?php echo __('  inkl. moms'); ?>
                                    </div>
                                </div>
                                <div class="ordered-details" >
                                    <?php $orderhelper = $block->getLayout()->createBlock('Zehntech\Reorder\Block\OrderDetails'); ?>
                                        <span><strong>Order Qty: </strong></span><?= $orderhelper->getTotalOrderedQty($_product->getSku());?>
                                        <br>
                                        <span><strong>Last Ordered: </strong></span><?= date("d-m-Y",strtotime($orderhelper->getLastOrderDate($_product->getSku())));?>
                                </div>
                                <!--test-->
                                <div class="product actions product-item-actions <?= $viewMode==='list'?'col-md-3 p-0':'' ?>"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                           <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                  action="<?= /* @NoEscape */
                                                  $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */
                                                $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */
                                                Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */
                                                $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                            <?php if($viewMode==="list"): ?>
                                                <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1)  ?>" steps="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" 
                                                class="input-text qty"/>
                                            <?php endif; ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */
                                                    __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */
                                                        __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                        __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links"
                                         class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                </div>

                                <!--test-->
                                
                                <!--test-->

                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?= /* @escapeNotVerified */
                                        $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?= /* @escapeNotVerified */
                                        $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */
                                        $_productNameStripped ?>"
                                           class="action more"><?= /* @escapeNotVerified */
                                            __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */
            $_product->getSku() ?>"
                }
            }
        }


        </script>
    <?php endif; ?>
<?php endif; ?>
