<?php
echo __('<h2>Popular products</h2>');
$popularProducts = $block->getPopularProducts();
$rem = (int)($popularProducts->getSize() / 8);
if ($remainder = $popularProducts->getSize() % 8) {
    $rem += $remainder;
}

?>

<div class="row w-100 mt-4">
    <div id="carouselExampleIndicators" class="carousel slide w-100" data-interval="2000" data-ride="carousel"
         style="overflow: hidden">
        <div class="carousel-inner" style="overflow: visible">

            <?php for ($i = 0;
                       $i < $rem;
                       $i++) { ?>

                <div class="carousel-item <?php if ($i == 0) {
                    echo "active";
                } ?>">
                    <div class=" row w-100 ml-0">

                        <?php
                        $j = 1;
                        foreach ($popularProducts as $product) {
                            ?>
                            <?php
                            if ($j < 9) {
                                echo "<div class='col-md-3 col-sm-3 slider-col pt-2 pb-2'>";
                                ?>
                                <div class="row w-100 ml-0 mt-2">
                                    <img class="product-img" alt="Pavetech"
                                         src="//<?php echo $product->getImageurl(); ?>">
                                </div>
                                <div class="row w-100 ml-0 mt-2">
                                    <a href="<?php echo $product->getProductUrl(); ?>"
                                       class="product-title"><?php echo $product->getName(); ?></a>
                                </div>

                                <div class="row w-100 ml-0 mt-2">
                                    <div class="col-md-6">
                                        <div class="row in-price">
                                            <?php echo $product->getFormattedPrice(); ?>
                                        </div>
                                        <div class="row ex-price">
                                            <?php echo $block->getFormattedPrice($block->getPriceWithVat($product)); ?>
                                        </div>
                                    </div>
                                    <div class="col-md-6 pr-0">
                                        <button class="add"><i class="fa fa-shopping-cart add-img"></i>
                                            <span><?php echo __('KOB') ?></span></button>
                                    </div>
                                </div>

                                <?php
                                echo "</div>";
                            }
                            ?>
                            <?php
                            $j++;
                        }
                        ?>
                    </div>
                </div>
                <?php 
            } ?>
        </div>
    </div>
    <a class="carousel-control-prev carousel-control-prev1" href="#carouselExampleIndicators" role="button"
               data-slide="prev">
               <i class="fa fa-angle-left"></i>

                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next carousel-control-next1" href="#carouselExampleIndicators" role="button"
               data-slide="next">
              <i class="fa fa-angle-right"></i>
                <span class="sr-only">Next</span>
    </a>
</div>


<!--<script type="text/javascript">-->
<!--    require(['bootstrap']);-->
<!--</script>-->

<script>// <![CDATA[
    require([
            'jquery',
            'bootstrap'
        ], function ($, bootstrap) {
            $('#carouselExampleIndicators').carousel({
                interval: false
            });
        }
    );
</script>