<?php
	$brandCollection = $block->getAllBrand();
?>

<div class="search-area">
	<div class="form-inline">
		<label>Søg:</label>
	  	<div class="form-group mx-sm-3 mb-2">
		    <select name="brand-search" id="searchBrand">
		    	<option value="0">Alle mærker</option>
		    	<?php
		    		foreach ($brandCollection as $brand) {
		    			if($brand['value']):
    			?>
		    		<option value="<?php echo $brand['value']; ?>"><?php echo $brand['label']; ?></option>		
    			<?php
    					endif;
		    		}
		    	 ?>
		    </select>
	  	</div>
	  	<div class="form-group">
	  		<input type="text" class="btn" name="name" id="searchInput" style="text-align"/>
  		</div>
	</div>
	<div>Select the brand and / or enter the model name or other keywords, such as Laserjet 4200, C11CB47101, etc.</div>
</div>
<div id="resultBrand">

	 <ul id="reasultBrandTable">

	 </ul>
</div>


<script>
    require([
        'jquery'
    ], function ($) {
    	var result;
    	$('#searchBrand').change(function(){
			$.get("http://127.0.0.1/kopen/seacrhbrand/brand/searchlist",{'brandId':this.value},function(data)
    		{
    			$('#reasultBrandTable').empty();
				li = '';
				if($('#searchBrand').val()!=0){
	    			data.productList.forEach(function(item){
						li = li+'<li><a href="'+item.url+'">'+item.name+'</a></li>';	
	    			});		
	    			$(li).appendTo('#reasultBrandTable');
	    		}	
    		});
    	});


		$('#searchInput').keyup(function(){
			$('#reasultBrandTable').empty();
			brandId = $('#searchBrand').val();

			$('#reasultBrandTable').empty();
    		$.get("http://127.0.0.1/kopen/seacrhbrand/brand/searchlist",{'brandId':brandId,'keySearch':this.value},function(data)
    		{
				li = '';
				$('#reasultBrandTable').empty();
    			data.productList.forEach(function(item){
						li = li+'<li><a href="'+item.url+'">'+item.name+'</a></li>';	
	    			});
    			$(li).appendTo('#reasultBrandTable');
    		});
		});


    });
</script>

<!-- if($('#searchBrand').val()!=0){
	   				li = '';
	   				data.productList.forEach(function(item){
	   					li = li + '<li><a href="'+item.url+'">'+item.name+'</a></li>';
	   				})
	   				console.log(li);
	   				$(li).appendTo('#reasultBrandTable');
	   			} -->