<div class="row ">
    <div class="col-6 banner-a">
    <a href="xerox-xrc-printerpatroner">
        <div class="banner-a-content  w-100 ">
            <span>Xerox XRC printerpatroner</span>        
        </div>
    </a>
    </div>
    <div class="col-6 banner-b">
    <a href="laser-blaekprintere">
        <div class="banner-b-content  w-100 ">   
            <span>Xerox MFP/laserprintere</span>     
        </div>
    </a>
    </div>
</div>