<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu2 = $block->getHtml('level-top', 'mega', $columnsLimit) ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php $_menu3 = $block->getCustomNav(241,true) ?>
<?php $_menu4 = $block->getCustomNav(243,true) ?>
<?php $_customNav = $block->getSelectedcatNav() ?>
<?php if ($block->allowExtension()): ?>
    <script>

        require([
            'jquery',
            'ibnabmodernizr'
        ], function ($) {


            $('.menu > ul > li:has( > ul)').addClass('menu-dropdown-icon');

            $('#header').append('<div class="popup-model"></div>');
            var toggle = "<a href=\"#\" class=\"menu-mobile\"><span class=\"fa fa-bars\"></span></a>"
            $(".menu > ul").before(toggle);
            $('a.level-top').click(function (e){
                if($(this).siblings().length){
                    e.preventDefault();
                }
            })
            $("#om > ul > li > a").click(function (e) {
               if($(this).siblings().length){
                    e.preventDefault(); //testing
                    if($(window).width() > 959) {

                        $('#om > ul > li').children('.category-list').hide();
                        $(this).siblings("ul").first().show(function(){
                            $(this).find(".level1.submenu.div-container").first().show();
                        });
                        firstLevel = $(this).siblings('.category-list').children('.first').children('a')
                        firstLevel.addClass('active-top')
                        $('.popup-model').show();
                        first = $(this).siblings('.category-list').find('.level1.first').children('.div-container');
                        first.show();
                        $('li.level1').hover(function(){
                                firstLevel.removeClass('active-top');
                            if($(this).hasClass('first'))
                                firstLevel.addClass('active-top')
                        },function(){
                            if($('li.level1:hover').length==0)
                                firstLevel.addClass('active-top');
                        })
                    }
                    else{
                        e.preventDefault();
                        $(this).siblings('.category-list').toggle();
                    }
                }
            });

            $('.level1.parent > a').click(function(e){
                e.preventDefault();
                $(this).siblings('.div-container').toggleClass('active-level');
            })

            $(".level1.div-container").hover(function(){
                $(this).siblings().toggleClass('active-top');
            })

            $('.popup-model').click(function(){
                var parent = $("li.menu-dropdown-icon"); 
                parent.children('ul').hide();
                parent.find('a').removeClass('active-top');
                // $(this).hide();
                $(this).toggle();
                if($(window).width()<960)
                {
                    $(".menu > ul").toggleClass('show-on-mobile');
                    $('.menu-close').toggleClass('cross-active',300);
                    $('#om > ul > li > ul').hide();
                    $('#om > ul > li > ul > .div-container').removeClass('active-level');
                    $('.div-container').removeClass('active-level');
                }
            }) 

            $(".menu-mobile").click(function (e) {
                $(".menu > ul").toggleClass('show-on-mobile');
                $('.menu-close').toggleClass('cross-active',300);
                // $('#header > .popup-model').toggleClass('popup-active');
                $('#header > .popup-model').toggle();
                e.preventDefault();
            });
            $('.menu-close').click(function(){
                $(".menu > ul").toggleClass('show-on-mobile');
                $(this).toggleClass('cross-active',300);
                // $('#header > .popup-model').toggleClass('popup-active');
                $('#header > .popup-model').toggle();
                $('#om > ul > li > ul').hide();
                $('.div-container').removeClass('active-level');
            })

            // if($(window).length<960)
            // {
            //     item = $('li.level1');
            //     if(item.find('.cat-column:has( > ul)').html())
            //     {
            //         // item.children('a').insertAfter("a").css({'content':'\f105','float':'right','margin-right':'21px','font':'normal normal normal 14px/1 FontAwesome'});
            //         item.children('a').addClass('fa fa-angle-right');
            //     }
            // }
        });

    </script>
    <?php
    /**
     * Top menu for store
     *
     * @see \Magento\Theme\Block\Html\Topmenu
     */
    ?>
    <nav class="navigation" role="navigation">

        <div class="menu" id="om">
            <ul>
                <?php /* @escapeNotVerified */
                echo $_menu2;
                // echo $_menu3; 
                // echo $_menu4;
                echo $_customNav;
            ?>
            </ul>
            <span class="menu-close fa fa-times"></span>
        </div>
        <ul id="dm"
            data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?php /* @escapeNotVerified */
            echo $_menu; ?>
        </ul>
    </nav>

<?php else : ?>

    <nav class="navigation" role="navigation">
        <?php /* @escapeNotVerified */
        echo $_menu; ?>
    </nav>
<?php endif; ?>
